// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventCode int32

const (
	EventCode_A EventCode = 0
	EventCode_B EventCode = 1
	EventCode_C EventCode = 2
)

var EventCode_name = map[int32]string{
	0: "A",
	1: "B",
	2: "C",
}

var EventCode_value = map[string]int32{
	"A": 0,
	"B": 1,
	"C": 2,
}

func (x EventCode) String() string {
	return proto.EnumName(EventCode_name, int32(x))
}

func (EventCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{0}
}

type EventWithCode struct {
	Type                 EventCode       `protobuf:"varint,1,opt,name=Type,proto3,enum=com.example.code.EventCode" json:"Type,omitempty"`
	EventA               *EventWithCodeA `protobuf:"bytes,2,opt,name=event_a,json=eventA,proto3" json:"event_a,omitempty"`
	EventB               *EventWithCodeB `protobuf:"bytes,3,opt,name=event_b,json=eventB,proto3" json:"event_b,omitempty"`
	EventC               *EventWithCodeC `protobuf:"bytes,4,opt,name=event_c,json=eventC,proto3" json:"event_c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EventWithCode) Reset()         { *m = EventWithCode{} }
func (m *EventWithCode) String() string { return proto.CompactTextString(m) }
func (*EventWithCode) ProtoMessage()    {}
func (*EventWithCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{0}
}

func (m *EventWithCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventWithCode.Unmarshal(m, b)
}
func (m *EventWithCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventWithCode.Marshal(b, m, deterministic)
}
func (m *EventWithCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithCode.Merge(m, src)
}
func (m *EventWithCode) XXX_Size() int {
	return xxx_messageInfo_EventWithCode.Size(m)
}
func (m *EventWithCode) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithCode.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithCode proto.InternalMessageInfo

func (m *EventWithCode) GetType() EventCode {
	if m != nil {
		return m.Type
	}
	return EventCode_A
}

func (m *EventWithCode) GetEventA() *EventWithCodeA {
	if m != nil {
		return m.EventA
	}
	return nil
}

func (m *EventWithCode) GetEventB() *EventWithCodeB {
	if m != nil {
		return m.EventB
	}
	return nil
}

func (m *EventWithCode) GetEventC() *EventWithCodeC {
	if m != nil {
		return m.EventC
	}
	return nil
}

type EventWithCodeA struct {
	A                    string   `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventWithCodeA) Reset()         { *m = EventWithCodeA{} }
func (m *EventWithCodeA) String() string { return proto.CompactTextString(m) }
func (*EventWithCodeA) ProtoMessage()    {}
func (*EventWithCodeA) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{1}
}

func (m *EventWithCodeA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventWithCodeA.Unmarshal(m, b)
}
func (m *EventWithCodeA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventWithCodeA.Marshal(b, m, deterministic)
}
func (m *EventWithCodeA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithCodeA.Merge(m, src)
}
func (m *EventWithCodeA) XXX_Size() int {
	return xxx_messageInfo_EventWithCodeA.Size(m)
}
func (m *EventWithCodeA) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithCodeA.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithCodeA proto.InternalMessageInfo

func (m *EventWithCodeA) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

type EventWithCodeB struct {
	A                    string   `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventWithCodeB) Reset()         { *m = EventWithCodeB{} }
func (m *EventWithCodeB) String() string { return proto.CompactTextString(m) }
func (*EventWithCodeB) ProtoMessage()    {}
func (*EventWithCodeB) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{2}
}

func (m *EventWithCodeB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventWithCodeB.Unmarshal(m, b)
}
func (m *EventWithCodeB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventWithCodeB.Marshal(b, m, deterministic)
}
func (m *EventWithCodeB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithCodeB.Merge(m, src)
}
func (m *EventWithCodeB) XXX_Size() int {
	return xxx_messageInfo_EventWithCodeB.Size(m)
}
func (m *EventWithCodeB) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithCodeB.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithCodeB proto.InternalMessageInfo

func (m *EventWithCodeB) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *EventWithCodeB) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type EventWithCodeC struct {
	A                    string                  `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64                   `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C                    *EventWithCodeC_Context `protobuf:"bytes,3,opt,name=C,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EventWithCodeC) Reset()         { *m = EventWithCodeC{} }
func (m *EventWithCodeC) String() string { return proto.CompactTextString(m) }
func (*EventWithCodeC) ProtoMessage()    {}
func (*EventWithCodeC) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{3}
}

func (m *EventWithCodeC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventWithCodeC.Unmarshal(m, b)
}
func (m *EventWithCodeC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventWithCodeC.Marshal(b, m, deterministic)
}
func (m *EventWithCodeC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithCodeC.Merge(m, src)
}
func (m *EventWithCodeC) XXX_Size() int {
	return xxx_messageInfo_EventWithCodeC.Size(m)
}
func (m *EventWithCodeC) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithCodeC.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithCodeC proto.InternalMessageInfo

func (m *EventWithCodeC) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *EventWithCodeC) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *EventWithCodeC) GetC() *EventWithCodeC_Context {
	if m != nil {
		return m.C
	}
	return nil
}

type EventWithCodeC_Context struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventWithCodeC_Context) Reset()         { *m = EventWithCodeC_Context{} }
func (m *EventWithCodeC_Context) String() string { return proto.CompactTextString(m) }
func (*EventWithCodeC_Context) ProtoMessage()    {}
func (*EventWithCodeC_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9b0151640170c3, []int{3, 0}
}

func (m *EventWithCodeC_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventWithCodeC_Context.Unmarshal(m, b)
}
func (m *EventWithCodeC_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventWithCodeC_Context.Marshal(b, m, deterministic)
}
func (m *EventWithCodeC_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithCodeC_Context.Merge(m, src)
}
func (m *EventWithCodeC_Context) XXX_Size() int {
	return xxx_messageInfo_EventWithCodeC_Context.Size(m)
}
func (m *EventWithCodeC_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithCodeC_Context.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithCodeC_Context proto.InternalMessageInfo

func (m *EventWithCodeC_Context) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *EventWithCodeC_Context) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("com.example.code.EventCode", EventCode_name, EventCode_value)
	proto.RegisterType((*EventWithCode)(nil), "com.example.code.EventWithCode")
	proto.RegisterType((*EventWithCodeA)(nil), "com.example.code.EventWithCodeA")
	proto.RegisterType((*EventWithCodeB)(nil), "com.example.code.EventWithCodeB")
	proto.RegisterType((*EventWithCodeC)(nil), "com.example.code.EventWithCodeC")
	proto.RegisterType((*EventWithCodeC_Context)(nil), "com.example.code.EventWithCodeC.Context")
}

func init() { proto.RegisterFile("code.proto", fileDescriptor_6e9b0151640170c3) }

var fileDescriptor_6e9b0151640170c3 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9d, 0xa6, 0x6d, 0xe8, 0xa8, 0x25, 0xec, 0x53, 0x50, 0x90, 0x10, 0x10, 0x82, 0xc8,
	0x0a, 0x15, 0x04, 0x1f, 0x77, 0x17, 0x2f, 0xb0, 0x08, 0x82, 0x2f, 0xd2, 0xa6, 0x0b, 0x0a, 0xb6,
	0x1b, 0x64, 0x91, 0xe4, 0x0c, 0x9e, 0xd6, 0x1b, 0xc8, 0x0c, 0x5b, 0x4b, 0x03, 0xda, 0x3e, 0x0d,
	0x33, 0xf3, 0x7f, 0x7f, 0xe6, 0x27, 0x8b, 0x58, 0xfb, 0xa5, 0x93, 0xcd, 0x87, 0x0f, 0x5e, 0x64,
	0xb5, 0x5f, 0x49, 0xd7, 0xce, 0x57, 0xcd, 0xbb, 0x93, 0x34, 0x2f, 0xbf, 0x01, 0x4f, 0x1f, 0x3e,
	0xdd, 0x3a, 0x3c, 0xbd, 0x85, 0x57, 0xe3, 0x97, 0x4e, 0xdc, 0xe0, 0xf0, 0xb1, 0x6b, 0x5c, 0x0e,
	0x05, 0x54, 0xd3, 0xd9, 0xb9, 0xec, 0x23, 0x92, 0xe5, 0x24, 0xb5, 0x2c, 0x14, 0xf7, 0x98, 0x3a,
	0x1a, 0xbd, 0xcc, 0xf3, 0x41, 0x01, 0xd5, 0xf1, 0xac, 0xf8, 0x83, 0xd9, 0x7c, 0x42, 0xd9, 0x31,
	0x03, 0x6a, 0x8b, 0x2e, 0xf2, 0xe4, 0x20, 0x54, 0x47, 0x54, 0x6f, 0xd1, 0x3a, 0x1f, 0x1e, 0x84,
	0x9a, 0x88, 0x9a, 0xf2, 0x02, 0xa7, 0xbb, 0xf7, 0x88, 0x13, 0x04, 0xc5, 0x81, 0x27, 0x16, 0x54,
	0x79, 0xdd, 0xdb, 0xeb, 0xdd, 0x3d, 0x75, 0x9a, 0xa3, 0x26, 0x16, 0x74, 0xf9, 0x05, 0x3d, 0xb9,
	0xf9, 0x4f, 0x2e, 0xee, 0x10, 0x4c, 0x0c, 0x5b, 0xed, 0xbb, 0x58, 0x1a, 0xbf, 0x0e, 0xae, 0x0d,
	0x16, 0xcc, 0xd9, 0x25, 0xa6, 0xb1, 0x23, 0xc3, 0x96, 0xed, 0x13, 0x0b, 0x2d, 0x75, 0xdd, 0xc6,
	0xbe, 0xbb, 0x2a, 0x70, 0xf2, 0xfb, 0x7f, 0xc4, 0x08, 0x41, 0x65, 0x47, 0x54, 0x74, 0x06, 0x54,
	0x4c, 0x36, 0xd0, 0xe9, 0xf3, 0x88, 0x1f, 0xc3, 0x62, 0xcc, 0xe5, 0xf6, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0xfd, 0x1a, 0xb8, 0x21, 0x02, 0x00, 0x00,
}
